/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ChainlinkOracleWrapperInterface extends ethers.utils.Interface {
  functions: {
    "deployer()": FunctionFragment;
    "fromWad(int256)": FunctionFragment;
    "getPrice()": FunctionFragment;
    "getPriceAndMetadata()": FunctionFragment;
    "oracle()": FunctionFragment;
    "poll()": FunctionFragment;
    "scaler()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fromWad",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPriceAndMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "oracle", values?: undefined): string;
  encodeFunctionData(functionFragment: "poll", values?: undefined): string;
  encodeFunctionData(functionFragment: "scaler", values?: undefined): string;

  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fromWad", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPriceAndMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "oracle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "scaler", data: BytesLike): Result;

  events: {};
}

export class ChainlinkOracleWrapper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ChainlinkOracleWrapperInterface;

  functions: {
    deployer(overrides?: CallOverrides): Promise<[string]>;

    fromWad(wad: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    getPrice(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _price: BigNumber }>;

    getPriceAndMetadata(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { _price: BigNumber; _data: string }>;

    oracle(overrides?: CallOverrides): Promise<[string]>;

    poll(overrides?: CallOverrides): Promise<[BigNumber]>;

    scaler(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  deployer(overrides?: CallOverrides): Promise<string>;

  fromWad(wad: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  getPrice(overrides?: CallOverrides): Promise<BigNumber>;

  getPriceAndMetadata(
    overrides?: CallOverrides
  ): Promise<[BigNumber, string] & { _price: BigNumber; _data: string }>;

  oracle(overrides?: CallOverrides): Promise<string>;

  poll(overrides?: CallOverrides): Promise<BigNumber>;

  scaler(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    deployer(overrides?: CallOverrides): Promise<string>;

    fromWad(wad: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getPriceAndMetadata(
      overrides?: CallOverrides
    ): Promise<[BigNumber, string] & { _price: BigNumber; _data: string }>;

    oracle(overrides?: CallOverrides): Promise<string>;

    poll(overrides?: CallOverrides): Promise<BigNumber>;

    scaler(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    deployer(overrides?: CallOverrides): Promise<BigNumber>;

    fromWad(wad: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    getPriceAndMetadata(overrides?: CallOverrides): Promise<BigNumber>;

    oracle(overrides?: CallOverrides): Promise<BigNumber>;

    poll(overrides?: CallOverrides): Promise<BigNumber>;

    scaler(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    deployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    fromWad(
      wad: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPriceAndMetadata(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    poll(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    scaler(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
