/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface PoolCommitterInterface extends ethers.utils.Interface {
  functions: {
    "LONG_INDEX()": FunctionFragment;
    "SHORT_INDEX()": FunctionFragment;
    "autoClaim()": FunctionFragment;
    "burnFeeHistory(uint256)": FunctionFragment;
    "claim(address)": FunctionFragment;
    "commit(uint8,uint256,bool,bool)": FunctionFragment;
    "executeCommitments()": FunctionFragment;
    "factory()": FunctionFragment;
    "getAggregateBalance(address)": FunctionFragment;
    "getAppropriateUpdateIntervalId()": FunctionFragment;
    "getPendingCommits()": FunctionFragment;
    "governance()": FunctionFragment;
    "initialize(address,address,address,uint256,uint256)": FunctionFragment;
    "invariantCheck()": FunctionFragment;
    "invariantCheckContract()": FunctionFragment;
    "lastUpdatedIntervalId(address)": FunctionFragment;
    "leveragedPool()": FunctionFragment;
    "pause()": FunctionFragment;
    "paused()": FunctionFragment;
    "priceHistory(uint256)": FunctionFragment;
    "setQuoteAndPool(address,address)": FunctionFragment;
    "tokens(uint256)": FunctionFragment;
    "totalPoolCommitments(uint256)": FunctionFragment;
    "unAggregatedCommitments(address,uint256)": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateAggregateBalance(address)": FunctionFragment;
    "updateIntervalId()": FunctionFragment;
    "userAggregateBalance(address)": FunctionFragment;
    "userCommitments(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "LONG_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SHORT_INDEX",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "autoClaim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burnFeeHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [string]): string;
  encodeFunctionData(
    functionFragment: "commit",
    values: [BigNumberish, BigNumberish, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "executeCommitments",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAggregateBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAppropriateUpdateIntervalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingCommits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "invariantCheck",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invariantCheckContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdatedIntervalId",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "leveragedPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuoteAndPool",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "tokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPoolCommitments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unAggregatedCommitments",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAggregateBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIntervalId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userAggregateBalance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userCommitments",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "LONG_INDEX", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SHORT_INDEX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "autoClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnFeeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAggregateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppropriateUpdateIntervalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingCommits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "invariantCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "invariantCheckContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdatedIntervalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "leveragedPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuoteAndPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPoolCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unAggregatedCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateAggregateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIntervalId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userAggregateBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCommitments",
    data: BytesLike
  ): Result;

  events: {
    "AggregateBalanceUpdated(address)": EventFragment;
    "Claim(address)": EventFragment;
    "CreateCommit(address,uint256,uint8,uint256,bytes16)": EventFragment;
    "ExecutedCommitsForInterval(uint256,bytes16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AggregateBalanceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreateCommit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutedCommitsForInterval"): EventFragment;
}

export class PoolCommitter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PoolCommitterInterface;

  functions: {
    LONG_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<[BigNumber]>;

    autoClaim(overrides?: CallOverrides): Promise<[string]>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    claim(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeCommitments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber] & {
          longTokens: BigNumber;
          shortTokens: BigNumber;
          settlementTokens: BigNumber;
        }
      ]
    >;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getPendingCommits(
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          longMintAmount: BigNumber;
          longBurnAmount: BigNumber;
          shortMintAmount: BigNumber;
          shortBurnAmount: BigNumber;
          shortBurnLongMintAmount: BigNumber;
          longBurnShortMintAmount: BigNumber;
          updateIntervalId: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          longMintAmount: BigNumber;
          longBurnAmount: BigNumber;
          shortMintAmount: BigNumber;
          shortBurnAmount: BigNumber;
          shortBurnLongMintAmount: BigNumber;
          longBurnShortMintAmount: BigNumber;
          updateIntervalId: BigNumber;
        }
      ]
    >;

    governance(overrides?: CallOverrides): Promise<[string]>;

    initialize(
      _factory: string,
      _invariantCheckContract: string,
      _autoClaim: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    invariantCheck(overrides?: CallOverrides): Promise<[string]>;

    invariantCheckContract(overrides?: CallOverrides): Promise<[string]>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    leveragedPool(overrides?: CallOverrides): Promise<[string]>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { longPrice: string; shortPrice: string }>;

    setQuoteAndPool(
      _quoteToken: string,
      _leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintAmount: BigNumber;
        longBurnAmount: BigNumber;
        shortMintAmount: BigNumber;
        shortBurnAmount: BigNumber;
        shortBurnLongMintAmount: BigNumber;
        longBurnShortMintAmount: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAggregateBalance(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateIntervalId(overrides?: CallOverrides): Promise<[BigNumber]>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        longTokens: BigNumber;
        shortTokens: BigNumber;
        settlementTokens: BigNumber;
      }
    >;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintAmount: BigNumber;
        longBurnAmount: BigNumber;
        balanceLongBurnAmount: BigNumber;
        shortMintAmount: BigNumber;
        shortBurnAmount: BigNumber;
        balanceShortBurnAmount: BigNumber;
        shortBurnLongMintAmount: BigNumber;
        balanceShortBurnMintAmount: BigNumber;
        longBurnShortMintAmount: BigNumber;
        balanceLongBurnMintAmount: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;
  };

  LONG_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  SHORT_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

  autoClaim(overrides?: CallOverrides): Promise<string>;

  burnFeeHistory(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  claim(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commit(
    commitType: BigNumberish,
    amount: BigNumberish,
    fromAggregateBalance: boolean,
    payForClaim: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeCommitments(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  factory(overrides?: CallOverrides): Promise<string>;

  getAggregateBalance(
    user: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      longTokens: BigNumber;
      shortTokens: BigNumber;
      settlementTokens: BigNumber;
    }
  >;

  getAppropriateUpdateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

  getPendingCommits(
    overrides?: CallOverrides
  ): Promise<
    [
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintAmount: BigNumber;
        longBurnAmount: BigNumber;
        shortMintAmount: BigNumber;
        shortBurnAmount: BigNumber;
        shortBurnLongMintAmount: BigNumber;
        longBurnShortMintAmount: BigNumber;
        updateIntervalId: BigNumber;
      },
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintAmount: BigNumber;
        longBurnAmount: BigNumber;
        shortMintAmount: BigNumber;
        shortBurnAmount: BigNumber;
        shortBurnLongMintAmount: BigNumber;
        longBurnShortMintAmount: BigNumber;
        updateIntervalId: BigNumber;
      }
    ]
  >;

  governance(overrides?: CallOverrides): Promise<string>;

  initialize(
    _factory: string,
    _invariantCheckContract: string,
    _autoClaim: string,
    _mintingFee: BigNumberish,
    _burningFee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  invariantCheck(overrides?: CallOverrides): Promise<string>;

  invariantCheckContract(overrides?: CallOverrides): Promise<string>;

  lastUpdatedIntervalId(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  leveragedPool(overrides?: CallOverrides): Promise<string>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  priceHistory(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { longPrice: string; shortPrice: string }>;

  setQuoteAndPool(
    _quoteToken: string,
    _leveragedPool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  totalPoolCommitments(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      longMintAmount: BigNumber;
      longBurnAmount: BigNumber;
      shortMintAmount: BigNumber;
      shortBurnAmount: BigNumber;
      shortBurnLongMintAmount: BigNumber;
      longBurnShortMintAmount: BigNumber;
      updateIntervalId: BigNumber;
    }
  >;

  unAggregatedCommitments(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAggregateBalance(
    user: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

  userAggregateBalance(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      longTokens: BigNumber;
      shortTokens: BigNumber;
      settlementTokens: BigNumber;
    }
  >;

  userCommitments(
    arg0: string,
    arg1: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      longMintAmount: BigNumber;
      longBurnAmount: BigNumber;
      balanceLongBurnAmount: BigNumber;
      shortMintAmount: BigNumber;
      shortBurnAmount: BigNumber;
      balanceShortBurnAmount: BigNumber;
      shortBurnLongMintAmount: BigNumber;
      balanceShortBurnMintAmount: BigNumber;
      longBurnShortMintAmount: BigNumber;
      balanceLongBurnMintAmount: BigNumber;
      updateIntervalId: BigNumber;
    }
  >;

  callStatic: {
    LONG_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    autoClaim(overrides?: CallOverrides): Promise<string>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    claim(user: string, overrides?: CallOverrides): Promise<void>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    executeCommitments(overrides?: CallOverrides): Promise<void>;

    factory(overrides?: CallOverrides): Promise<string>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        longTokens: BigNumber;
        shortTokens: BigNumber;
        settlementTokens: BigNumber;
      }
    >;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendingCommits(
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          longMintAmount: BigNumber;
          longBurnAmount: BigNumber;
          shortMintAmount: BigNumber;
          shortBurnAmount: BigNumber;
          shortBurnLongMintAmount: BigNumber;
          longBurnShortMintAmount: BigNumber;
          updateIntervalId: BigNumber;
        },
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          longMintAmount: BigNumber;
          longBurnAmount: BigNumber;
          shortMintAmount: BigNumber;
          shortBurnAmount: BigNumber;
          shortBurnLongMintAmount: BigNumber;
          longBurnShortMintAmount: BigNumber;
          updateIntervalId: BigNumber;
        }
      ]
    >;

    governance(overrides?: CallOverrides): Promise<string>;

    initialize(
      _factory: string,
      _invariantCheckContract: string,
      _autoClaim: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    invariantCheck(overrides?: CallOverrides): Promise<string>;

    invariantCheckContract(overrides?: CallOverrides): Promise<string>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    leveragedPool(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { longPrice: string; shortPrice: string }>;

    setQuoteAndPool(
      _quoteToken: string,
      _leveragedPool: string,
      overrides?: CallOverrides
    ): Promise<void>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintAmount: BigNumber;
        longBurnAmount: BigNumber;
        shortMintAmount: BigNumber;
        shortBurnAmount: BigNumber;
        shortBurnLongMintAmount: BigNumber;
        longBurnShortMintAmount: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        longTokens: BigNumber;
        shortTokens: BigNumber;
        settlementTokens: BigNumber;
      }
    >;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        longMintAmount: BigNumber;
        longBurnAmount: BigNumber;
        balanceLongBurnAmount: BigNumber;
        shortMintAmount: BigNumber;
        shortBurnAmount: BigNumber;
        balanceShortBurnAmount: BigNumber;
        shortBurnLongMintAmount: BigNumber;
        balanceShortBurnMintAmount: BigNumber;
        longBurnShortMintAmount: BigNumber;
        balanceLongBurnMintAmount: BigNumber;
        updateIntervalId: BigNumber;
      }
    >;
  };

  filters: {
    AggregateBalanceUpdated(
      user?: string | null
    ): TypedEventFilter<[string], { user: string }>;

    Claim(user?: string | null): TypedEventFilter<[string], { user: string }>;

    CreateCommit(
      user?: string | null,
      amount?: BigNumberish | null,
      commitType?: BigNumberish | null,
      appropriateUpdateIntervalId?: null,
      mintingFee?: null
    ): TypedEventFilter<
      [string, BigNumber, number, BigNumber, string],
      {
        user: string;
        amount: BigNumber;
        commitType: number;
        appropriateUpdateIntervalId: BigNumber;
        mintingFee: string;
      }
    >;

    ExecutedCommitsForInterval(
      updateIntervalId?: BigNumberish | null,
      burningFee?: null
    ): TypedEventFilter<
      [BigNumber, string],
      { updateIntervalId: BigNumber; burningFee: string }
    >;
  };

  estimateGas: {
    LONG_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<BigNumber>;

    autoClaim(overrides?: CallOverrides): Promise<BigNumber>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claim(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeCommitments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPendingCommits(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _factory: string,
      _invariantCheckContract: string,
      _autoClaim: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    invariantCheck(overrides?: CallOverrides): Promise<BigNumber>;

    invariantCheckContract(overrides?: CallOverrides): Promise<BigNumber>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    leveragedPool(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setQuoteAndPool(
      _quoteToken: string,
      _leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAggregateBalance(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateIntervalId(overrides?: CallOverrides): Promise<BigNumber>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    LONG_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    SHORT_INDEX(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    autoClaim(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burnFeeHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commit(
      commitType: BigNumberish,
      amount: BigNumberish,
      fromAggregateBalance: boolean,
      payForClaim: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeCommitments(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAggregateBalance(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAppropriateUpdateIntervalId(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPendingCommits(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      _factory: string,
      _invariantCheckContract: string,
      _autoClaim: string,
      _mintingFee: BigNumberish,
      _burningFee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    invariantCheck(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    invariantCheckContract(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastUpdatedIntervalId(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    leveragedPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceHistory(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setQuoteAndPool(
      _quoteToken: string,
      _leveragedPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalPoolCommitments(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unAggregatedCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAggregateBalance(
      user: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateIntervalId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userAggregateBalance(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userCommitments(
      arg0: string,
      arg1: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
